### ISSUE TITLE
private_key & public_key files

### ISSUE THREAD

**Issue by karolisbarkauskas** [talandis/laravel-banklinks#1]
Hello

    'private_key' => '',
    'public_key' => '',

should be plaintext or path to files?

**Comment by talandis** [comment]
Path to files,  e.g.
'private_key' => base_path('config/certificates/.../...-private.key')

**Comment by karolisbarkauskas** [comment]
hm,

I get an error ,,openssl_sign(): supplied key param cannot be coerced into a private key"
keys pats:

    'private_key' => base_path('config/certificates/swedbank/private_key.pem'),
    'public_key' => base_path('config/certificates/swedbank/rsa.crt'),

As I see 
        openssl_sign($hash, $signature, $keyId);


signature and key id is empty

**Comment by talandis** [comment]
Just checked the sample in readme. 
It mentions that setConfiguration() is optional but seems it doesn't work if you don't call it manually.
